# Generated by Django 5.1.2 on 2024-10-17 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('stop', models.TimeField()),
                ('ids', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('slots', models.ManyToManyField(to='schedule.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='schedule.dayschedule')),
                ('monday', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='schedule.dayschedule')),
                ('saturday', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='schedule.dayschedule')),
                ('sunday', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday', to='schedule.dayschedule')),
                ('thursday', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='schedule.dayschedule')),
                ('tuesday', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='schedule.dayschedule')),
                ('wednesday', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='schedule.dayschedule')),
            ],
        ),
    ]
